const server = require('./src/app.js');
const { conn, Lotes } = require('./src/db.js');
const PORT = process.env.PORT || 3001;
const lotesData = [
 { Lotes: 'LMV-01'},
  {Lotes: 'SMOOV-01'},
  {Lotes: 'LMV-07'},
 { Lotes: 'LMV-04'},
  {Lotes: 'LMV-03'},
  {Lotes: 'LMV-02'},
  {Lotes: 'LMV-05'},
  {Lotes: 'LMV-06'},
  {Lotes: 'LMV-09'},
 { Lotes: 'LMV-08'},
  {Lotes: 'LMV-10'},
  {Lotes: 'LMV-10'},
 { Lotes: 'LCOM-01'},
  {Lotes: 'NST-08'},
 { Lotes: 'NST-14'},
  {Lotes: 'NST-06'},
  {Lotes: 'NST-12'},
 { Lotes: 'NST-10'},
  {Lotes: 'NST-05'},
  {Lotes: 'NST-11'},
  {Lotes: 'NST-15'},
  {Lotes: 'NST-09'},
  {Lotes: 'NST-13'},
  {Lotes: 'NST-07'},
  {Lotes: 'NST-01'},
 { Lotes: 'NST-04'},
  {Lotes: 'NST-02'},
  {Lotes: 'CALD-04'},
  {Lotes: 'CALD-05'},
  {Lotes: 'CALD-03'},
 { Lotes: 'CALD-02'},
  {Lotes: 'ELDTP-07'},
  {Lotes: 'SUV-09'},
  {Lotes: 'SUV-02'},
  {Lotes: 'SUV-06'},
{  Lotes: 'SUV-03'},
  {Lotes: 'SUV-15'},
  {Lotes: 'SUV-12'},
  {Lotes: 'SUV-20'},
  {Lotes: 'SUV-08'},
  {Lotes: 'SUV-30'},
  {Lotes: 'SUV-11'},
 { Lotes: 'SUV-10'},
 { Lotes: 'SUV-28'},
  {Lotes: 'SUV-21'},
  {Lotes: 'SUV-01'},
 { Lotes: 'SUV-23'},
 { Lotes: 'SUV-05'},
  {Lotes: 'SUV-18'},
  {Lotes: 'SUV-25'},
  {Lotes: 'SUV-29'},
  {Lotes: 'SUV-22'},
 { Lotes: 'SUV-07'},
{  Lotes: 'SUV-31'},
  {Lotes: 'SUV-17'},
  {Lotes: 'SUV-16'},
  {Lotes: 'SUV-13'},
 { Lotes: 'SUV-26'},
  {Lotes: 'SUV-24'},
  {Lotes: 'SUV-19'},
  {Lotes: 'SUV-14'},
  {Lotes: 'SUV-27'},
 { Lotes: 'CA-05'},
 { Lotes: 'CA-04'},
  {Lotes: 'CA-24'},
  {Lotes: 'CA-17'},
  {Lotes: 'CA-16'},
 { Lotes: 'CA-15'},
  {Lotes: 'CA-23'},
  {Lotes: 'CA-14'},
 { Lotes: 'CA-20'},
  {Lotes: 'CA-09'},
  {Lotes: 'CA-11'},
  {Lotes: 'CA-12'},
  {Lotes: 'CA-22'},
  {Lotes: 'CA-07'},
  {Lotes: 'CA-21'},
  {Lotes: 'CA-01'},
  {Lotes: 'CA-08'},
  {Lotes: 'CA-26'},
 { Lotes: 'CA-06'},
  {Lotes: 'CA-02'},
  {Lotes: 'CA-13'},
  {Lotes: 'CA-03'},
  {Lotes: 'CA-10'},
  {Lotes: 'CA-19'},
  {Lotes: 'CA-18'},
 { Lotes: 'CA-25'},
  {Lotes: 'SND-02'},
  {Lotes: 'SND-05'},
  {Lotes: 'SND-12'},
  {Lotes: 'SND-03'},
  {Lotes: 'SND-01'},
  {Lotes: 'SND-07'},
  {Lotes: 'SND-15'},
  {Lotes: 'SND-08'},
 { Lotes: 'SND-13'},
  {Lotes: 'SND-14'},
  {Lotes: 'SND-04'},
  {Lotes: 'SND-11'},
{  Lotes: 'SND-09'},
  {Lotes: 'SND-06'},
  {Lotes: 'SND-10'},
 { Lotes: 'MELP-14'},
  {Lotes: 'MELP-04'},
  {Lotes: 'MELP-01'},
 { Lotes: 'MELP-15'},
  {Lotes: 'MELP-05'},
  {Lotes: 'MELP-03'},
 { Lotes: 'MELP-11'},
  {Lotes: 'MELP-06'},
 { Lotes: 'MELP-12'},
  {Lotes: 'MELP-09'},
 { Lotes: 'MELP-08'},
 { Lotes: 'MELP-13'},
  {Lotes: 'MELP-07'},
  {Lotes: 'MELP-02'},
  {Lotes: 'MELP-10'},
 { Lotes: 'CL-02'},
 { Lotes: 'CL-03'},
 { Lotes: 'CL-10'},
  {Lotes: 'CL-14'},
  {Lotes: 'CL-01'},
  {Lotes: 'CL-09'},
  {Lotes: 'CL-13'},
  {Lotes: 'CL-12'},
 { Lotes: 'CL-15'},
 { Lotes: 'CL-05'},
  {Lotes: 'CL-07'},
{  Lotes: 'CL-08'},
{  Lotes: 'CL-06'},
 { Lotes: 'CL-11'},
  {Lotes: 'CL-04'},
 { Lotes: 'PEM-07'},
  {Lotes: 'PEM-11'},
 { Lotes: 'PEM-06'},
{  Lotes: 'PEM-05'},
  {Lotes: 'PEM-10'},
 { Lotes: 'PEM-12'},
  {Lotes: 'PEM-08'},
  {Lotes: 'PEM-04'},
  {Lotes: 'PEM-13'},
  {Lotes: 'PEM-09'},
  {Lotes: 'PEM-14'},
 { Lotes: 'SMOOV-04'},
  {Lotes: 'SMOOV-05'},
{  Lotes: 'SMOOV-02'},
 { Lotes: 'SMOOV-03'},
 { Lotes: 'SMOOV-01'},
{  Lotes: 'SMOOV-08'},
  {Lotes: 'SMOOV-07'},
  {Lotes: 'SMOOV-06'},
  {Lotes: 'SMOOV-11'},
 { Lotes: 'SMOOV-09'},
  {Lotes: 'SMOOV-10'},
{  Lotes: 'AOV-03'},
 { Lotes: 'AOV-08'},
 { Lotes: 'AOV-07'},
{  Lotes: 'AOV-04'},
{  Lotes: 'AOV-02'},
  {Lotes: 'AOV-01'}
 
];
conn.sync({ force: false }).then(async () => {
  // Ejemplo de cómo agregar un nuevo Lead a la base de datos
  try {
    await Lotes.bulkCreate(lotesData);

    console.log('Datos agregados a la base de datos');

    server.listen(PORT, () => {
      console.log(`Servidor corriendo en el puerto ${PORT}`);
    });
  } catch (error) {
    console.error('Error al agregar datos a la base de datos:', error);
  }
});

/* conn.sync({ force: false }).then(() => {
  server.listen(PORT, () => {
    console.log(`Servidor corriendo en el puerto ${PORT}`);
  });
}); */
